name: build-sphinx-docs

on:
  push:
    branches: [ dev ]

  workflow_dispatch:

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
           python-version: "3.11"
        
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install Sphinx>=7.4.7 sphinx_rtd_theme>=2.0.0

      - name: Build HTML
        run: | 
          cd docs/
          make html

      - name: Run ghp-import
        run: | 
          ghp-import -n -p -f docs/_build/html
