name: build-sphinx-docs

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
           python-version: "3.12"

      - name: Build and install package
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Install docs dependencies
        run: |
          pip install -r docs/requirements.txt

      - name: Build HTML
        run: | 
          cd docs/
          make html

      - name: Run ghp-import
        run: | 
          ghp-import -n -p -f docs/_build/html
